# Generated by Django 5.2.5 on 2025-08-27 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='Product',
            new_name='product',
        ),
    ]
